type User {
  id: String!
  name: String!
}

type Query {
  user(id: String!): User
}

input CreateUserInput {
  name: String!
}

type Mutation {
  createUser(createUserInput: CreateUserInput): User
}
